
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.1.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/pressly/goose"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gocraft/work"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/blaskovicz/go-cryptkeeper"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/qor/admin"

[[constraint]]
  branch = "master"
  name = "github.com/qor/qor"

[[override]]
  branch = "master"
  name = "github.com/qor/roles"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/iReflect/go-pivotaltracker"
  branch = "master"
